### PR TITLE
fix to be without Tagged Template on index.js

### PR DESCRIPTION
**Pull request by tgfjt**
`uglifyjs` can't parse bel component.

```
observe-resize (feature/tagged_template*) λ  uglifyjs ./index.js
Parse error at ./index.js:19,18
  var frame = html`<iframe class="__observe-resize__"></iframe>`
                  ^
SyntaxError: Unexpected character '`'
```

This error occured when I run `browserify with-nanocomponent.js -t es2020 -t | uglifyjs bundle.js`.
`nanocomponent` uses `observe-resize` which uses bel.

### CODE REVIEW

**Review by yoshuawuyts — APPROVED** [review]
fair enough (:

**Comment by yoshuawuyts** [comment]
`v1.1.3`

**Comment by tgfjt** [comment]
bedankt!

**Comment by yoshuawuyts** [comment]
いいえ、どいたしまして！

**Pull request merged**
