### PR TITLE
Fix: make the library not error in Node

### PR DESCRIPTION
**Pull request by ajoslin**
We use "insert-styles" instead of "insert-css" because it doesn't error in Node.

And then we use `typeof window` to abort in a non-browser environment.

### CODE REVIEW

**Comment by ajoslin** [comment]
If/when you merge, can you update the dep in nanocomponent as well? Thanks!

**Review by yoshuawuyts — APPROVED** [review]
neatoooo

**Comment by yoshuawuyts** [comment]
`v1.1.2` - thanks! Change should propagate upwards so try running `npm install` and you'll have the new version :sparkles:

**Comment by ajoslin** [comment]
Aha, of course, forgot about semver. Thanks!

**Pull request merged**
